# Generated by Django 2.1.15 on 2020-07-13 16:32

import core.models.order_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.order_model.order_image_file_name),
        ),
    ]
